# Homework 1

In [22]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("../data/car_fuel_efficiency_2026.csv")

df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

Q2. Records count

In [4]:
df.count()

model_year             10000
origin                 10000
fuel_type              10000
drivetrain             10000
num_doors              10000
engine_displacement    10000
num_cylinders          10000
horsepower              9123
vehicle_weight         10000
acceleration            9736
fuel_efficiency_mpg    10000
dtype: int64

Q3. Fuel types

In [5]:
df["fuel_type"].unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

Q4. Missing values

In [6]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

Q5. Max fuel efficiency

In [7]:
df[df["origin"] == "Asia"]["fuel_efficiency_mpg"].max()

np.float64(41.2)

Q6. Median value of horsepower

In [8]:
median = df["horsepower"].median()

print(median)

254.0

In [9]:
frec = df["horsepower"].value_counts().idxmax()
print(frec)

252.0

In [10]:
df.fillna(frec)

median_02 = df["horsepower"].median()

print(median_02)

254.0

Q7. Sum of weights

In [18]:
asia_cars = df[df["origin"] == "Asia"][["vehicle_weight", "model_year"]]

asia_cars.head(7)

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [24]:
X = asia_cars.head(7).values
print(X)

[[4240 1996]
 [4310 1992]
 [4230 1997]
 [4420 1978]
 [3950 2007]
 [4750 2021]
 [4450 2019]]

In [28]:
XTX = X.T @ X
print(XTX)

[[131950500  60750580]
 [ 60750580  28041424]]

In [29]:
inv_XTX = np.linalg.inv(XTX)

In [31]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
print(y)

[1100 1300  800  900 1000 1100 1200]

In [32]:
w = (inv_XTX @ X.T) @ y
print(w)

[0.13644777 0.2327492 ]

In [33]:
w.sum()

np.float64(0.36919696904925486)